stages:
  prepare:
    cmd: python src/data/make_dataset.py
    deps:
      - src/data/make_dataset.py
      - data/raw/UCI_Credit_Card.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
    params:
      - prepare.test_size
      - prepare.random_state

  validate:
    cmd: python src/data/validation.py
    deps:
      - src/data/validation.py
      - data/processed/train.csv
    outs:
      - data/expectations/credit_data_suite.json

  train:
    cmd: python src/models/train.py
    deps:
      - src/models/train.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - models/credit_default_model.joblib
    metrics:
      - metrics/model_metrics.json:
          cache: false
    params:
      - train.model_type
      - train.random_state

vars:
  - prepare.test_size: 0.2
  - prepare.random_state: 42
  - train.model_type: "GradientBoosting"
  - train.random_state: 42